language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm
before_script:
  - composer selfupdate
  - composer install
script:
  - phpunit
after_success:
  - chmod +x test/publishCoverage.sh
  - test/publishCoverage.sh
matrix:
  allow_failures:
    - php: hhvm
